# Generated by Django 4.0.3 on 2022-04-08 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=80)),
                ('fone', models.CharField(blank=True, max_length=15, null=True)),
                ('ativo', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=main.models.upload_image_user)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
