# Generated by Django 4.0.4 on 2022-04-29 17:13

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(upload_to=main.models.upload_image_user),
        ),
    ]
